### PR TITLE
Add .NET Core support

### PR DESCRIPTION
**Pull request by am11**
A simple C# .NET implementation for YAML editor.

I am unable to test it, because haskell container is failing to build:

image

I tried updating the base container to 8.6 (https://hub.docker.com/_/haskell), but it possesses a different issues that the non-interactivity is lost and user is expected to type "yes" to accept certificate, followed by permission denied error at "hackage" installation step.

### CODE REVIEW

**Comment by perlpunk** [comment]
Thanks!  This looks good at a first glance. Will hopefully have time to integrate it (and look into the haskell problem)

**Comment by perlpunk** [comment]
Sorry that I didn't have time earlier.

I built the docker image successfully with your PR, but now I need to know where the binary ends up.
What do I need to call to produce event output? I cannot find `dotnet-event` anywhere in the image.

**Comment by am11** [comment]
Thank you for taking a look.

I was unable to test the flow earlier to the point where i could launch the editor with dotnet.event, due to the blocking Haskell issue. I just realized that it is not necessary a "all or none" kind of a deal, and that we can comment out `ghc-binaries \` line in `docker/Makefile` to get unblocked. :D

To test, please try:

```sh
git clone https://github.com/am11/yaml-editor --single-branch --branch master --depth 1
cd yaml-editor

# comment out haskell line for a time-being
sed -i 's/ghc-binaries \\/# &/g' ./docker/Makefile

# source
. .rc

# compile everything and run dotnet.event editor
yaml-editor -cg dotnet.event
```

There were few things I updated  to make it work.

* updated to .NET Core 3.0, so to publish as a single file (new feature).
  * latest state of .NET Core 3.0 is release-candidate 2. the (rumored) release date is September 23. I have used the major/minor version (without preview tag) to keep it future proof.
* although Alpine Linux image is super snappy (4.15MB base vs. 79.6MB of Ubuntu base), i realized that the runtime container from yamlio is Ubuntu x64, glibc based, which maps to .NET RID `linux-x64`; therefore the Alpine Linux build container using `linux-musl-x64` .NET RuntimeID would not work. So I have changed it to glibc based upstream container.
* added missing runtime dependency on ICU libs package required by globalization.
  * we can also opt-out of globalization and use invariant culture without this dependency by setting `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1`. but it seems like a peanut compared to the chain of dependencies already being installed.
* YDN version from 6.0 to 6.1.2, which includes a more standard conformant parser. :)

**Comment by am11** [comment]
Updated steps to test:

```sh
git clone https://github.com/yaml/yaml-editor
cd yaml-editor

# apply this patch
curl -L https://github.com/yaml/yaml-editor/pull/21.patch | git apply -v

# disable perl5 in Dockerfile
sed -i '/perl5-modules \\/d' docker/Makefile

# source
. .rc

# compile
yaml-editor -c dotnet.event
```

**Comment by perlpunk** [comment]
This is now obsolete as the new YAML editor is built from https://github.com/yaml/yaml-runtimes and .Net was added there:
https://github.com/yaml/yaml-runtimes/pull/2

Thanks!

**Pull request closed without merging**
